### ISSUE TITLE
Error handling refactoring

### ISSUE THREAD

**Issue by DieTime** [andreyhoco/OS_labs#4]
The length of the message may not fit in 150 or 50 characters.

```c
void print_type_error(char* file_name) {
	char msg[150];
	strncpy(msg, file_name, strlen(file_name));
	strncat(msg, ": unexpected file type\n\0", 150 - strlen(": unexpected file type\n\0") + 1);
	write(2, msg, strlen(msg) + 1);
}

void print_error(int errornum, char* file_name) {
	char *error_description = strerror(errornum);
	char error_msg[50];
	strncpy(error_msg, file_name, 48);
	strncat(error_msg, ": ", 48 - strlen(error_msg));
	strncat(error_msg, error_description, 48 - strlen(error_msg));
	strncat(error_msg, "\n\0", 50 - strlen(error_msg));
	write(2, error_msg, strlen(error_msg) + 1);
}
```

As I understand it, this approach with `write`, `strncpy` and `strncat` was due to the fact that the error must be written to `STDERR`. Instead it, you can use the `fprintf(stderr, ...)` function and do not create buffers yourself.

**Comment by andreyhoco** [comment]
Increased the size of the displayed messages. In this assignment, it was necessary to use descriptors, without stdio.h. Thx.
